# Don't print a new line at the start of the prompt
add_newline = false

format = """
${custom.username}\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$python\
$line_break\
$character"""

[character]
symbol = "âœ"

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = false

[python]
pyenv_version_name = true
symbol = "ğŸ"
format = 'via [${symbol}${version}${symbol}]($style) '

[custom.username]
command = "echo å´”"
when = "true"
